[site_info]
  created_at = "2024-10-23"
  bei_an = "暂无"
  title = "12311"
  qq_image = "_"
  version = ""
  email = "xiyingqing777@gmail.com"
  wechat_image = "_"
  name = "xyq"
  job = "后端"
  addr = "江西南昌"
  slogan = "xyq777"
  slogan_en = "xyq777"
  web = "xyq777.org"
  bilibili_url = "_"
  gitee_url = "_"
  github_url = "github/Xyq777"
[qq]
app-id= "xx"
key= "xx"
redirect= "http://xx.xx.com/login?flag=qq"
[email]
host="smtp.qq.com"
port= 465
user= "xxx@qq.com"
password= ""
default_from_email= ""
use-ssl= ""
user-tls= ""
[qi_niu]
access_key= ""
secret_key=  ""
bucket= ""
cdn=""
zone= ""
size= 5
